export const CREATE_PROJECT = "CREATE_PROJECT";

export const GET_ALL_PROJECTS = "GET_ALL_PROJECTS";

export const POST_PROJECT = "POST_PROJECT";
export const POST_PROJECT_SUCCESS = "POST_PROJECT_SUCCESS";
export const POST_PROJECT_FAILURE = "POST_PROJECT_FAILURE";

export const STORE_PROJECTS = "STORE_PROJECTS";

export const STORE_PROJECT = "STORE_PROJECT";

export const DELETE_PROJECT = "DELETE_PROJECT";

export const ADD_PROJECT_TASK = "ADD_PROJECT_TASK";
export const ADD_PROJECT_TASK_SUCCESS = "ADD_PROJECT_TASK_SUCCESS";
export const ADD_PROJECT_TASK_FAILURE = "ADD_PROJECT_TASK_FAILURE";

export const GET_PROJECT_TASKS = "GET_PROJECT_TASKS";
export const GET_PROJECT_TASKS_SUCCESS = "GET_PROJECT_TASKS_SUCCESS";
export const GET_PROJECT_TASKS_FAILURE = "GET_PROJECT_TASKS_FAILURE";

export const GET_PROJECT_TASK = "GET_PROJECT_TASK";
export const STORE_PROJECT_TASK = "STORE_PROJECT_TASK";

export const PATCH_PROJECT_TASK = "PATCH_PROJECT_TASK";
export const PATCH_PROJECT_TASK_SUCCESS = "PATCH_PROJECT_TASK_SUCCESS";
export const PATCH_PROJECT_TASK_FAILURE = "PATCH_PROJECT_TASK_FAILURE";

export const DELETE_PROJECT_TASK = "DELETE_PROJECT_TASK";
export const DELETE_PROJECT_TASK_SUCCESS = "DELETE_PROJECT_TASK_SUCCESS";
export const DELETE_PROJECT_TASK_FAILURE = "DELETE_PROJECT_TASK_FAILURE";
