export const CREATE_PROJECT = "CREATE_PROJECT";

export const GET_ALL_PROJECTS = "GET_ALL_PROJECTS";

export const POST_PROJECT = "POST_PROJECT";
export const POST_PROJECT_SUCCESS = "POST_PROJECT_SUCCESS";
export const POST_PROJECT_FAILURE = "POST_PROJECT_FAILURE";

export const STORE_PROJECTS = "STORE_PROJECTS";

export const STORE_PROJECT = "STORE_PROJECT";

export const DELETE_PROJECT = "DELETE_PROJECT";
